# Generated by Django 5.1.7 on 2025-03-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_change_7d', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_change_30d', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_change_60d', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_change_90d', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
